version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  name: draw-and-guess-game-$(date +%Y%m%d-%H%M%S)
